//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentInfo
    {
        public int sId { get; set; }
        public string sName { get; set; }
        public bool sGender { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime sBirthday { get; set; }
        public string sPhone { get; set; }
        public string sEMail { get; set; }
        public int cid { get; set; }
    
        public virtual ClassInfo ClassInfo { get; set; }
    }
}
